spring.application.name=smartscore
server.port=8080
server.servlet.context-path=/api
spring.ai.openai.api-key=${GEMINI_KEY}
spring.ai.openai.chat.base-url=https://generativelanguage.googleapis.com
spring.ai.openai.chat.completions-path=/v1beta/openai/chat/completions
spring.ai.openai.chat.options.model=gemini-2.0-flash
spring.datasource.url=jdbc:mysql://localhost:3306/smartscore
spring.datasource.username=vuongnvh
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false